version: '3.7'
services:
  app:
    build: .
    depends_on: 
      - pair_mongodb
    environment: 
      token: secret
    restart: always

  pair_mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_pair:/data/db

volumes:
  mongodb_pair:
